title: Manish Sharma | Computer Vision and Deep Learning Researcher
email: ms8515@rit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Manish Sharma, PhD student at Rochester Institute of Technology, specializing in computer vision, deep learning, machine learning, and image processing. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: manish_sharma # if you have a Twitter account
github_username:  ms1594 # if you have a GitHub account

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Add # more to this list to exclude other files or directories.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

